/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module ripple_carry_adder_4(sum, cout, in1, in2, cin);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire \FA1.sum ;
  wire \FA2.sum ;
  wire \FA3.sum ;
  wire \FA4.sum ;
  input cin;
  output cout;
  input [3:0] in1;
  input [3:0] in2;
  output [3:0] sum;
  NAND2_X1 _24_ (
    .A1(in2[0]),
    .A2(in1[0]),
    .ZN(_00_)
  );
  NOR2_X2 _25_ (
    .A1(in2[0]),
    .A2(in1[0]),
    .ZN(_01_)
  );
  INV_X1 _26_ (
    .A(cin),
    .ZN(_02_)
  );
  OAI21_X2 _27_ (
    .A(_00_),
    .B1(_01_),
    .B2(_02_),
    .ZN(_03_)
  );
  NAND2_X2 _28_ (
    .A1(_03_),
    .A2(in2[1]),
    .ZN(_04_)
  );
  NOR2_X2 _29_ (
    .A1(_03_),
    .A2(in2[1]),
    .ZN(_05_)
  );
  INV_X1 _30_ (
    .A(in1[1]),
    .ZN(_06_)
  );
  OAI21_X2 _31_ (
    .A(_04_),
    .B1(_05_),
    .B2(_06_),
    .ZN(_07_)
  );
  XOR2_X1 _32_ (
    .A(in2[2]),
    .B(in1[2]),
    .Z(_08_)
  );
  NAND2_X2 _33_ (
    .A1(_07_),
    .A2(_08_),
    .ZN(_09_)
  );
  NAND2_X1 _34_ (
    .A1(in2[2]),
    .A2(in1[2]),
    .ZN(_10_)
  );
  NAND2_X2 _35_ (
    .A1(_09_),
    .A2(_10_),
    .ZN(_11_)
  );
  XOR2_X1 _36_ (
    .A(in2[3]),
    .B(in1[3]),
    .Z(_12_)
  );
  NAND2_X2 _37_ (
    .A1(_11_),
    .A2(_12_),
    .ZN(_13_)
  );
  NAND2_X1 _38_ (
    .A1(in2[3]),
    .A2(in1[3]),
    .ZN(_14_)
  );
  NAND2_X1 _39_ (
    .A1(_13_),
    .A2(_14_),
    .ZN(cout)
  );
  INV_X1 _40_ (
    .A(_12_),
    .ZN(_15_)
  );
  NAND3_X1 _41_ (
    .A1(_09_),
    .A2(_15_),
    .A3(_10_),
    .ZN(_16_)
  );
  NAND2_X2 _42_ (
    .A1(_13_),
    .A2(_16_),
    .ZN(_17_)
  );
  INV_X2 _43_ (
    .A(_17_),
    .ZN(\FA4.sum )
  );
  INV_X1 _44_ (
    .A(_00_),
    .ZN(_18_)
  );
  NOR2_X1 _45_ (
    .A1(_18_),
    .A2(_01_),
    .ZN(_19_)
  );
  XNOR2_X1 _46_ (
    .A(_19_),
    .B(_02_),
    .ZN(\FA1.sum )
  );
  INV_X1 _47_ (
    .A(_04_),
    .ZN(_20_)
  );
  OR2_X1 _48_ (
    .A1(_20_),
    .A2(_05_),
    .ZN(_21_)
  );
  XNOR2_X1 _49_ (
    .A(_21_),
    .B(_06_),
    .ZN(_22_)
  );
  INV_X1 _50_ (
    .A(_22_),
    .ZN(\FA2.sum )
  );
  XNOR2_X1 _51_ (
    .A(_07_),
    .B(_08_),
    .ZN(_23_)
  );
  INV_X1 _52_ (
    .A(_23_),
    .ZN(\FA3.sum )
  );
  assign sum = { \FA4.sum , \FA3.sum , \FA2.sum , \FA1.sum  };
endmodule
