/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module carry_lookahead_adder_4(sum, cout, in1, in2, cin);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  input cin;
  output cout;
  input [3:0] in1;
  input [3:0] in2;
  output [3:0] sum;
  NAND2_X1 _22_ (
    .A1(in2[0]),
    .A2(in1[0]),
    .ZN(_00_)
  );
  NOR2_X2 _23_ (
    .A1(in2[0]),
    .A2(in1[0]),
    .ZN(_01_)
  );
  INV_X1 _24_ (
    .A(cin),
    .ZN(_02_)
  );
  OAI21_X4 _25_ (
    .A(_00_),
    .B1(_01_),
    .B2(_02_),
    .ZN(_03_)
  );
  XOR2_X2 _26_ (
    .A(in2[1]),
    .B(in1[1]),
    .Z(_04_)
  );
  NAND2_X2 _27_ (
    .A1(_03_),
    .A2(_04_),
    .ZN(_05_)
  );
  NAND2_X1 _28_ (
    .A1(in2[1]),
    .A2(in1[1]),
    .ZN(_06_)
  );
  NAND2_X4 _29_ (
    .A1(_05_),
    .A2(_06_),
    .ZN(_07_)
  );
  XOR2_X2 _30_ (
    .A(in2[2]),
    .B(in1[2]),
    .Z(_08_)
  );
  NAND2_X4 _31_ (
    .A1(_07_),
    .A2(_08_),
    .ZN(_09_)
  );
  NAND2_X1 _32_ (
    .A1(in2[2]),
    .A2(in1[2]),
    .ZN(_10_)
  );
  NAND2_X4 _33_ (
    .A1(_09_),
    .A2(_10_),
    .ZN(_11_)
  );
  XOR2_X2 _34_ (
    .A(in2[3]),
    .B(in1[3]),
    .Z(_12_)
  );
  NAND2_X4 _35_ (
    .A1(_11_),
    .A2(_12_),
    .ZN(_13_)
  );
  NAND2_X1 _36_ (
    .A1(in2[3]),
    .A2(in1[3]),
    .ZN(_14_)
  );
  NAND2_X1 _37_ (
    .A1(_13_),
    .A2(_14_),
    .ZN(cout)
  );
  INV_X1 _38_ (
    .A(_00_),
    .ZN(_15_)
  );
  NOR2_X1 _39_ (
    .A1(_15_),
    .A2(_01_),
    .ZN(_16_)
  );
  XNOR2_X1 _40_ (
    .A(_16_),
    .B(cin),
    .ZN(_17_)
  );
  INV_X1 _41_ (
    .A(_17_),
    .ZN(sum[0])
  );
  XOR2_X1 _42_ (
    .A(_03_),
    .B(_04_),
    .Z(sum[1])
  );
  XNOR2_X1 _43_ (
    .A(_07_),
    .B(_08_),
    .ZN(_18_)
  );
  INV_X1 _44_ (
    .A(_18_),
    .ZN(sum[2])
  );
  INV_X1 _45_ (
    .A(_12_),
    .ZN(_19_)
  );
  NAND3_X1 _46_ (
    .A1(_09_),
    .A2(_10_),
    .A3(_19_),
    .ZN(_20_)
  );
  NAND2_X2 _47_ (
    .A1(_13_),
    .A2(_20_),
    .ZN(_21_)
  );
  INV_X2 _48_ (
    .A(_21_),
    .ZN(sum[3])
  );
endmodule
