/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module adder_8(sum, cout, in1, in2, cin);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire \FA1.sum ;
  wire \FA2.sum ;
  wire \FA3.sum ;
  wire \FA4.sum ;
  wire \FA5.sum ;
  wire \FA6.sum ;
  wire \FA7.sum ;
  wire \FA8.sum ;
  input cin;
  output cout;
  input [7:0] in1;
  input [7:0] in2;
  output [7:0] sum;
  NAND2_X1 _42_ (
    .A1(in2[0]),
    .A2(in1[0]),
    .ZN(_00_)
  );
  NOR2_X1 _43_ (
    .A1(in2[0]),
    .A2(in1[0]),
    .ZN(_01_)
  );
  INV_X1 _44_ (
    .A(cin),
    .ZN(_02_)
  );
  OAI21_X2 _45_ (
    .A(_00_),
    .B1(_01_),
    .B2(_02_),
    .ZN(_03_)
  );
  XOR2_X2 _46_ (
    .A(in2[1]),
    .B(in1[1]),
    .Z(_04_)
  );
  NAND2_X2 _47_ (
    .A1(_03_),
    .A2(_04_),
    .ZN(_05_)
  );
  NAND2_X1 _48_ (
    .A1(in2[1]),
    .A2(in1[1]),
    .ZN(_06_)
  );
  NAND2_X4 _49_ (
    .A1(_05_),
    .A2(_06_),
    .ZN(_07_)
  );
  XOR2_X2 _50_ (
    .A(in2[2]),
    .B(in1[2]),
    .Z(_08_)
  );
  XNOR2_X1 _51_ (
    .A(_07_),
    .B(_08_),
    .ZN(_09_)
  );
  INV_X1 _52_ (
    .A(_09_),
    .ZN(\FA3.sum )
  );
  NAND2_X4 _53_ (
    .A1(_07_),
    .A2(_08_),
    .ZN(_10_)
  );
  NAND2_X1 _54_ (
    .A1(in2[2]),
    .A2(in1[2]),
    .ZN(_11_)
  );
  NAND2_X4 _55_ (
    .A1(_10_),
    .A2(_11_),
    .ZN(_12_)
  );
  XOR2_X2 _56_ (
    .A(in2[3]),
    .B(in1[3]),
    .Z(_13_)
  );
  XNOR2_X1 _57_ (
    .A(_12_),
    .B(_13_),
    .ZN(_14_)
  );
  INV_X1 _58_ (
    .A(_14_),
    .ZN(\FA4.sum )
  );
  NAND2_X4 _59_ (
    .A1(_12_),
    .A2(_13_),
    .ZN(_15_)
  );
  NAND2_X1 _60_ (
    .A1(in2[3]),
    .A2(in1[3]),
    .ZN(_16_)
  );
  NAND2_X4 _61_ (
    .A1(_15_),
    .A2(_16_),
    .ZN(_17_)
  );
  XOR2_X1 _62_ (
    .A(in2[4]),
    .B(in1[4]),
    .Z(_18_)
  );
  XNOR2_X1 _63_ (
    .A(_17_),
    .B(_18_),
    .ZN(_19_)
  );
  INV_X1 _64_ (
    .A(_19_),
    .ZN(\FA5.sum )
  );
  NAND2_X4 _65_ (
    .A1(_17_),
    .A2(_18_),
    .ZN(_20_)
  );
  NAND2_X1 _66_ (
    .A1(in2[4]),
    .A2(in1[4]),
    .ZN(_21_)
  );
  NAND2_X4 _67_ (
    .A1(_20_),
    .A2(_21_),
    .ZN(_22_)
  );
  XOR2_X1 _68_ (
    .A(in2[5]),
    .B(in1[5]),
    .Z(_23_)
  );
  XNOR2_X1 _69_ (
    .A(_22_),
    .B(_23_),
    .ZN(_24_)
  );
  INV_X1 _70_ (
    .A(_24_),
    .ZN(\FA6.sum )
  );
  NAND2_X4 _71_ (
    .A1(_22_),
    .A2(_23_),
    .ZN(_25_)
  );
  NAND2_X1 _72_ (
    .A1(in2[5]),
    .A2(in1[5]),
    .ZN(_26_)
  );
  NAND2_X4 _73_ (
    .A1(_25_),
    .A2(_26_),
    .ZN(_27_)
  );
  XOR2_X1 _74_ (
    .A(in2[6]),
    .B(in1[6]),
    .Z(_28_)
  );
  XNOR2_X1 _75_ (
    .A(_27_),
    .B(_28_),
    .ZN(_29_)
  );
  INV_X1 _76_ (
    .A(_29_),
    .ZN(\FA7.sum )
  );
  NAND2_X4 _77_ (
    .A1(_27_),
    .A2(_28_),
    .ZN(_30_)
  );
  NAND2_X1 _78_ (
    .A1(in2[6]),
    .A2(in1[6]),
    .ZN(_31_)
  );
  NAND2_X4 _79_ (
    .A1(_30_),
    .A2(_31_),
    .ZN(_32_)
  );
  XOR2_X1 _80_ (
    .A(in2[7]),
    .B(in1[7]),
    .Z(_33_)
  );
  NAND2_X4 _81_ (
    .A1(_32_),
    .A2(_33_),
    .ZN(_34_)
  );
  NAND2_X1 _82_ (
    .A1(in2[7]),
    .A2(in1[7]),
    .ZN(_35_)
  );
  NAND2_X1 _83_ (
    .A1(_34_),
    .A2(_35_),
    .ZN(cout)
  );
  INV_X1 _84_ (
    .A(_33_),
    .ZN(_36_)
  );
  NAND3_X1 _85_ (
    .A1(_30_),
    .A2(_31_),
    .A3(_36_),
    .ZN(_37_)
  );
  NAND2_X2 _86_ (
    .A1(_34_),
    .A2(_37_),
    .ZN(_38_)
  );
  INV_X2 _87_ (
    .A(_38_),
    .ZN(\FA8.sum )
  );
  INV_X1 _88_ (
    .A(_00_),
    .ZN(_39_)
  );
  NOR2_X1 _89_ (
    .A1(_39_),
    .A2(_01_),
    .ZN(_40_)
  );
  XNOR2_X1 _90_ (
    .A(_40_),
    .B(cin),
    .ZN(_41_)
  );
  INV_X1 _91_ (
    .A(_41_),
    .ZN(\FA1.sum )
  );
  XOR2_X1 _92_ (
    .A(_03_),
    .B(_04_),
    .Z(\FA2.sum )
  );
  assign sum = { \FA8.sum , \FA7.sum , \FA6.sum , \FA5.sum , \FA4.sum , \FA3.sum , \FA2.sum , \FA1.sum  };
endmodule
