/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module counter(clk, reset, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  input clk;
  output [3:0] q;
  input reset;
  NOR2_X1 _19_ (
    .A1(q[0]),
    .A2(reset),
    .ZN(_00_)
  );
  NAND2_X1 _20_ (
    .A1(q[0]),
    .A2(q[1]),
    .ZN(_04_)
  );
  INV_X1 _21_ (
    .A(_04_),
    .ZN(_05_)
  );
  NOR2_X1 _22_ (
    .A1(q[0]),
    .A2(q[1]),
    .ZN(_06_)
  );
  NOR3_X1 _23_ (
    .A1(_05_),
    .A2(_06_),
    .A3(reset),
    .ZN(_01_)
  );
  NAND3_X2 _24_ (
    .A1(q[0]),
    .A2(q[1]),
    .A3(q[2]),
    .ZN(_07_)
  );
  INV_X1 _25_ (
    .A(q[2]),
    .ZN(_08_)
  );
  NAND2_X1 _26_ (
    .A1(_04_),
    .A2(_08_),
    .ZN(_09_)
  );
  INV_X1 _27_ (
    .A(reset),
    .ZN(_10_)
  );
  AND3_X2 _28_ (
    .A1(_07_),
    .A2(_09_),
    .A3(_10_),
    .ZN(_02_)
  );
  INV_X1 _29_ (
    .A(q[3]),
    .ZN(_11_)
  );
  NAND2_X2 _30_ (
    .A1(_07_),
    .A2(_11_),
    .ZN(_12_)
  );
  NAND2_X2 _31_ (
    .A1(_12_),
    .A2(_10_),
    .ZN(_13_)
  );
  NOR2_X1 _32_ (
    .A1(_07_),
    .A2(_11_),
    .ZN(_14_)
  );
  NOR2_X2 _33_ (
    .A1(_13_),
    .A2(_14_),
    .ZN(_03_)
  );
  DFF_X1 _34_ (
    .CK(clk),
    .D(_00_),
    .Q(q[0]),
    .QN(_15_)
  );
  DFF_X1 _35_ (
    .CK(clk),
    .D(_01_),
    .Q(q[1]),
    .QN(_16_)
  );
  DFF_X1 _36_ (
    .CK(clk),
    .D(_02_),
    .Q(q[2]),
    .QN(_17_)
  );
  DFF_X1 _37_ (
    .CK(clk),
    .D(_03_),
    .Q(q[3]),
    .QN(_18_)
  );
endmodule
